# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 793c05864c09fb92dec5aae0bd279ca9c2d3e342296c9e73f9fcd09eb81f835e5afffb2e0e8ca5f453407c8abd7d45958ca55e1953f3c4879238fe6f9ca80834

test:
  secret_key_base: 7eda8afef304af9570c16c66f27fa40372038c0739653e2a149631fc51a009d20801bf8a5f5e5425e990bf449afa80f4cf073b380e5a76c27161269d1880a6f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
